Presentation/Typer.Web/Controllers/AdminSeasonController.cs
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Views.AdminSeason;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class AdminSeasonController : Controller
    {
        private readonly IAdminSeasonService _adminSeasonService;
        public AdminSeasonController(IAdminSeasonService adminSeasonService)
        {
            _adminSeasonService = adminSeasonService;
        }

        public ActionResult Index()
        {
            var model = _adminSeasonService.GetAdminSeasonIndex();
            return View(model);
        }

        public ActionResult AddNewSeason()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddNewSeason(VMAdminSeasonCreate model)
        {
            _adminSeasonService.AddNewSeason(model);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Typer.Web/Views/AdminSeason/AddNewSeason.cshtml
@model Typer.ViewModels.Views.AdminSeason.VMAdminSeasonCreate


<h2>Dodaj sezon</h2>
<div class="col-md-6">
    @using (Html.BeginForm("AddNewSeason", "AdminSeason", FormMethod.Post))
    {
        @Html.EditorFor(x => x)
        <button type="submit">Zapisz</button>
    }
</div>

Presentation/Typer.Web/Views/AdminSeason/Index.cshtml
@model Typer.ViewModels.Views.AdminSeason.VMAdminSeasonIndex

@{
    ViewBag.Title = "Index";
}

<div class="row page-header">
    <div class="col-md-11">
        <h4 class="headline-title">Zarządzaj sezonami</h4>
    </div>
    <div class="col-md-1">
        @Html.ActionLink("Dodaj sezon", "AddNewSeason", "AdminSeason", null, new { @class = "btn btn-default" })
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @foreach (var season in Model.Seasons)
        {
            <div class="row">
                <p>@(season.StartYear + "/" + season.EndYear)</p>
            </div>
        }
    </div>
</div>