Presentation/Typer.Web/Controllers/AdminMatchweekController.cs
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Views.AdminMatchweek;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class AdminMatchweekController : Controller
    {
        private readonly IAdminSeasonService _adminSeasonService;
        private readonly IAdminMatchweekService _adminMatchweekService;

        public AdminMatchweekController(IAdminSeasonService adminSeasonService, 
                                        IAdminMatchweekService adminMatchweekService)
        {
            _adminSeasonService = adminSeasonService;
            _adminMatchweekService = adminMatchweekService;
        }

        public ActionResult Index()
        {
            var model = _adminMatchweekService.GetAdminMatchweekIndex();
            return View(model);
        }

        public ActionResult Create()
        {
            var seasons = _adminSeasonService.GetSeasonSelectList();
            var model = new VMAdminMatchweekCreate
            {
                Seasons = seasons
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(VMAdminMatchweekCreate model)
        {
            _adminMatchweekService.CreateMatchweek(model);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Typer.Web/Views/AdminMatchweek/Create.cshtml
@model Typer.ViewModels.Views.AdminMatchweek.VMAdminMatchweekCreate

<h2>Dodaj kolejkę</h2>
<div class="col-md-6">
    @using (Html.BeginForm("Create", "AdminMatchweek", FormMethod.Post))
    {
        @Html.EditorFor(x => x.MatchweekName)
        @Html.DropDownListFor(x => x.SeasonId, Model.Seasons)
        <button  type="submit">Zapisz</button>
    }
</div>

Presentation/Typer.Web/Views/AdminMatchweek/Index.cshtml
@model Typer.ViewModels.Views.AdminMatchweek.VMAdminMatchweekIndex
    @{ 
        ViewBag.Title = "Kolejki";
    }

<div class="row page-header">
    <div class="col-md-11">
        <h4 class="headline-title">Zarządzaj kolejkami</h4>
    </div>
    <div class="col-md-1">
        @Html.ActionLink("Dodaj kolejkę", "Create", "AdminMatchweek", null, new { @class = "btn btn-default" })
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @foreach (var matchweek in Model.Matchweeks)
        {
            <div class="row">
                <p>@matchweek.MatchweekName</p>
            </div>
        }
    </div>
</div>