Presentation/Typer.Web/Controllers/AdminController.cs
using System.Web.Mvc;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }       
    }
}

Presentation/Typer.Web/Controllers/CalendarController.cs
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Views.Calendar;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class CalendarController : Controller
    {
        private readonly ICalendarService _calendarService;

        public CalendarController(ICalendarService calendarService)
        {
            _calendarService = calendarService;
        }

        public ActionResult Index()
        {
            var seasonsSelectList = _calendarService.GetSeasonSelectList();
            return View(new VMCalendarIndex { SelectListSeasons = seasonsSelectList });
        }

        [HttpGet]
        public PartialViewResult GetMatches(int seasonId)
        {
            var model = _calendarService.GetCalendarIndex(seasonId);
            return PartialView("CalendarPartial", model);
        }        
    }
}

Presentation/Typer.Web/Controllers/ProfileController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Views.Profile;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IProfileService _userProfileService;
        private readonly IAdminTeamService _adminTeamService;

        public ProfileController (IProfileService userProfileService, IAdminTeamService adminTeamService)
        {
            _userProfileService = userProfileService;
            _adminTeamService = adminTeamService;
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var model = _userProfileService.GetUserDetails(userId);
            model.SelectListTeams = _adminTeamService.GetTeamsSelectList();
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangeDetails(VMManageIndex details)
        {
            details.Id = User.Identity.GetUserId();
            _userProfileService.ChangeUserDetails(details);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Typer.Web/Controllers/TyperController.cs
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Common;
using Typer.ViewModels.Views.Typer;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class TyperController : Controller
    {
        private readonly ITyperService _typerService;

        public TyperController(ITyperService typerService)
        {
            _typerService = typerService;
        }

        public ActionResult Index()
        {
            var model = new VMTyperIndex { Matches = _typerService.GetTyperIndexMatches(User.Identity.GetUserId()) };
            return View(model);
        }

        public ActionResult ChangeMatchPredictions(VMTyperIndex model)
        {
            var userId = User.Identity.GetUserId();
            _typerService.ChangeMatchPredictions(model, userId);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Typer.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Typer</title>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/date-picker/datepicker.css">
    <script src="~/Scripts/date-picker/datepicker.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top col-md-12">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("TYPER", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="sidemenu col-md-2">
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <span class="glyphicon glyphicon-th">
                        </span>Panel administracyjny
                    </h4>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-flash"></span>@Html.ActionLink("Zespoły", "Index", "AdminTeam")
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file"></span>@Html.ActionLink("Mecze", "Index", "AdminMatch")
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file"></span>@Html.ActionLink("Wyniki", "MatchScores", "AdminMatch")
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file"></span>@Html.ActionLink("Kolejki", "Index", "AdminMatchweek")
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file"></span>@Html.ActionLink("Sezony", "Index", "AdminSeason")
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <div class="col-md-9">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Presentation/Typer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Typer</title>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/date-picker/datepicker.css">
    <script src="~/Scripts/date-picker/datepicker.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TYPER", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Typuj", "Index", "Typer", null, new { @class = "navbar-brand" } )
                @Html.ActionLink("Terminarz", "Index", "Calendar", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Statystyki", "Index", "Statistic", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Kontakt", "Index", "Profile", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Dodaj klub","Index", "AdminTeam" )</li>
                    <li>@Html.ActionLink("Wyświetl listę zespołów", "ShowTeams", "AdminTeam")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.ActionLink("AdminPanel", "Index", "Admin")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>