Presentation/Typer.Web/Controllers/AdminMatchController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Typer.Services.Interfaces;
using Typer.ViewModels.Views.AdminMatch;

namespace Typer.Web.Controllers
{
    [Authorize]
    public class AdminMatchController : Controller
    {
        private readonly IAdminMatchService _adminMatchService;
        private readonly IAdminSeasonService _adminSeasonService;
        private readonly IAdminMatchweekService _adminMatchweekService;
        private readonly IAdminTeamService _adminTeamService;

        public AdminMatchController(IAdminMatchService adminMatchService,
                                    IAdminSeasonService adminSeasonService,
                                    IAdminMatchweekService adminMatchweekService,
                                    IAdminTeamService adminTeamService)
        {
            _adminMatchService = adminMatchService;
            _adminSeasonService = adminSeasonService;
            _adminMatchweekService = adminMatchweekService;
            _adminTeamService = adminTeamService;
        }

        public ActionResult Index()
        {
            var model = _adminMatchService.GetAdminMatchIndex();
            return View(model);
        }

        public ActionResult Create()
        {
            var season = _adminSeasonService.GetSeasonSelectList();
            var teams = _adminTeamService.GetTeamsSelectList();
            var model = new VMAdminMatchCreate
            {
                Seasons = season,
                Matchweeks = new SelectList(new List<string>()),
                Teams = teams
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(VMAdminMatchCreate model)
        {
            _adminMatchService.CreateMatch(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetGameweekList(int seasonId)
        {
            var matchweeks = _adminMatchweekService.GetMatchweekSelectList(seasonId);
            return Json(matchweeks, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MatchScores()
        {
            var model = _adminMatchService.GetAdminMatchIndex();
            return View(model);
        }

        public ActionResult CreateMatchScore()
        {
            var model = _adminMatchService.GetAdminMatchIndex();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateMatchScore(VMAdminMatchIndex model)
        {
            _adminMatchService.CreateMatchScore(model);
            return RedirectToAction("MatchScores");
        }
    }
}

Presentation/Typer.Web/Views/AdminMatch/Create.cshtml
@model Typer.ViewModels.Views.AdminMatch.VMAdminMatchCreate


<h2>Dodaj mecz</h2>

<div class="col-md-6">
    @using (Html.BeginForm("Create", "AdminMatch", FormMethod.Post))
    {
        <div class="form-group row">
            @Html.DropDownListFor(x => x.SeasonId, Model.Seasons, new { @id = "seasonList" })
        </div>
        <div class="form-group row">
            @Html.DropDownListFor(x => x.MatchweekId, Model.Matchweeks, new { @id = "matchweekList" })
        </div>
        <div class="form-group row">
            @Html.DropDownListFor(x => x.HomeTeamId, Model.Teams)
        </div>
        <div class="form-group row">
            @Html.DropDownListFor(x => x.AwayTeamId, Model.Teams)
        </div>
        <div class="form-group row">
            <input type="text" class="form-control" name="MatchDate" id="MatchDate" data-toggle="datepicker">
        </div>
        <button type="submit">Zapisz</button>
    }
</div>

<script>
    $(function () {
        $('[data-toggle="datepicker"]').datepicker({
            autoHide: true,
            autoPick: true,
            date: @DateTime.Now.ToBinary(),
            format: 'yyyy-mm-dd'
        });
    });

    $(document).ready(function () {        
        loadMatchweeks();        
    })

    $("#seasonList").change(function () {
        loadMatchweeks();
    })

    function loadMatchweeks()
    {
        var seasonId = $("#seasonList").val();
        $.ajax
            ({
                type: 'POST',
                url: '@Url.Action("GetGameweekList")',
                dataType: 'json',
                data: { seasonId: seasonId },
                success: function (response)
                {
                    var matchweeks = $("#matchweekList");
                    matchweeks.empty();
                    $.each(response, function (index, item) {
                        var option = $('<option/>');
                        option.attr({ 'value': item.Value }).text(item.Text);
                        matchweeks.append(option);
                    });
                }
            })
    }

</script>

Presentation/Typer.Web/Views/AdminMatch/CreateMatchScore.cshtml
@model Typer.ViewModels.Views.AdminMatch.VMAdminMatchIndex

@{
    ViewBag.Title = "CreateMatchScore";
}

<h2>Edytuj wyniki</h2>

@using (Html.BeginForm("CreateMatchScore", "AdminMatch", FormMethod.Post))
{
    for (int i=0; i<Model.Matches.Count; i++)
    {
        @Html.HiddenFor(x => Model.Matches[i].MatchId)
        <div class="row">
            <div class="col-md-2">
                <p>@Model.Matches[i].HomeTeamName</p>
            </div>
            <div class="col-md-2">
                @Html.EditorFor(x => Model.Matches[i].HomeTeamGoals)
            </div>
            <div class="col-md-2">
                @Html.EditorFor(x => Model.Matches[i].AwayTeamGoals)
            </div>
            <div class="col-md-2">
                @Model.Matches[i].AwayTeamName
            </div>
        </div>
    }
    <button type="submit">Zapisz</button>

}

Presentation/Typer.Web/Views/AdminMatch/Index.cshtml
@model Typer.ViewModels.Views.AdminMatch.VMAdminMatchIndex

@{ 
    ViewBag.Title = "Index";
}

<div class="row page-header">
    <div class="col-md-11">
        <h4 class="headline-title">Zarządzaj meczami</h4>
    </div>
    <div class="col-md-1">
        @Html.ActionLink("Dodaj mecz", "Create", "AdminMatch", null, new { @class = "btn btn-default" })
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @foreach (var match in Model.Matches)
        {
            <div class="row">
                <p>@($"{match.HomeTeamName} - {match.AwayTeamName}")</p>
            </div>
        }
    </div>
</div>

Presentation/Typer.Web/Views/AdminMatch/MatchScores.cshtml
@model Typer.ViewModels.Views.AdminMatch.VMAdminMatchIndex

@{
    ViewBag.Title = "MatchScores";
}

<div class="row page-header">
    <div class="col-md-11">
        <h4 class="headline-title">Zarządzaj wynikami</h4>
    </div>
    <div class="col-md-1">
        @Html.ActionLink("Edytuj wyniki", "CreateMatchScore", "AdminMatch", null, new { @class = "btn btn-default" })
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @foreach (var match in Model.Matches)
        {
            <div class="row">
                <div class="col-md-2">@match.HomeTeamName</div>
                <div class="col-md-2">@match.HomeTeamGoals</div>
                <div class="col-md-2">@match.AwayTeamGoals</div>
                <div class="col-md-2">@match.AwayTeamName</div>
            </div>
        }
    </div>
</div>